[tool.poetry]
name = "warehouse_backend"
version = "0.1.0"
description = ""
authors = ["Vika"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
psycopg2 = "^2.9.10"
gunicorn = "^23.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
