# Generated by Django 5.2 on 2025-04-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0002_remove_user_email_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
