# Generated by Django 5.2 on 2025-04-28 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0003_alter_category_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.user'),
        ),
    ]
