# Generated by Django 5.2 on 2025-04-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0004_category_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
    ]
