# Generated by Django 5.2 on 2025-05-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0005_rename_user_id_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='telegram_id',
        ),
    ]
