# Generated by Django 5.2 on 2025-05-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0006_rename_user_category_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='telegram_id',
            new_name='user',
        ),
    ]
