# Generated by Django 5.2 on 2025-05-29 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0008_alter_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='location',
            name='type_of_location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.AddField(
            model_name='product',
            name='location_of_purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_of_purchase', to='warehouse_app.location'),
        ),
        migrations.AddField(
            model_name='product',
            name='location_of_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_of_sale', to='warehouse_app.location'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
