# Generated by Django 5.2 on 2025-06-17 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0009_remove_location_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='warehouse_app.user'),
            preserve_default=False,
        ),
    ]
